org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.7-beta


mod_id=chest_vows
mod_name=Chest Item: Vows
mod_license=All Rights Reserved
mod_version=1.0.0.5
mod_group_id=com.ytgld.chest_vows